openapi: 3.0.3
info:
  title: Property API
  version: 0.0.0
  description: API for Property
paths:
  /api/:
    get:
      operationId: api_retrieve
      description: A simple Viewset for viewing all categories
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
