# Generated by Django 4.2.6 on 2023-10-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.AlterUniqueTogether(
            name='propertyattributevalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='propertyattributevalue',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='propertyattributevalue',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='property_line',
        ),
        migrations.RemoveField(
            model_name='propertyline',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='propertyline',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='propertyline',
            name='property',
        ),
        migrations.AlterUniqueTogether(
            name='propertylineattributevalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='propertylineattributevalue',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='propertylineattributevalue',
            name='property_line',
        ),
        migrations.AlterUniqueTogether(
            name='propertytypeattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='propertytypeattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='propertytypeattribute',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='PropertyAttributeValue',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.DeleteModel(
            name='PropertyLine',
        ),
        migrations.DeleteModel(
            name='PropertyLineAttributeValue',
        ),
        migrations.DeleteModel(
            name='PropertyTypeAttribute',
        ),
    ]
