# Generated by Django 4.2.6 on 2023-10-30 11:46

from django.db import migrations
import property.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='order',
            field=property.fields.OrderField(blank=True, default=0),
        ),
    ]
